<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<Version>1.0.0</Version>
	</PropertyGroup>

	<PropertyGroup>
		<PackageId>WSCT.GUI.ACOS6Launcher</PackageId>
		<Description>Launcher of WSCT GUI configured with ACOS6 plugins.</Description>
		<ApplicationIcon></ApplicationIcon>
	</PropertyGroup>

	<PropertyGroup>
		<UseWindowsForms>true</UseWindowsForms>
		<Win32Resource />
		<StartupObject />
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="WSCT.GUI" />
		<PackageReference Include="WSCT.GUI.Plugins.LayerInteractive" />
		<PackageReference Include="WSCT.Plugin.ISO7816Tools" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Plugin ACOS6\Plugin ACOS6.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="Stack.Channel.xml">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Stack.Context.xml">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>