<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Library</OutputType>
		<Version>1.0.0.0</Version>
	</PropertyGroup>

	<PropertyGroup>
		<PackageId>WSCT.Layers.ACOS6.UnitTests</PackageId>
		<Description>Unit tests for WSCT.Layers.ACOS6 library.</Description>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="Moq" />
		<PackageReference Include="NUnit" />
		<PackageReference Include="NUnit3TestAdapter">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Layer ACOS6\Layer ACOS6.csproj" />
	</ItemGroup>
</Project>