<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<VersionPrefix>1.0.0</VersionPrefix>
		<VersionSuffix></VersionSuffix>
	</PropertyGroup>

	<PropertyGroup>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<VersionPrefix>1.0.0</VersionPrefix>
		<VersionSuffix></VersionSuffix>
		<RootNamespace>WSCT.ACOS6.CommandLine</RootNamespace>
		<AssemblyName>wsct-acos6</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" />
		<PackageReference Include="Spectre.Console" />
		<PackageReference Include="Spectre.Console.Cli" />
		<PackageReference Include="WSCT.Wrapper.Desktop" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\WSCT.ACOS6\WSCT.ACOS6.csproj" />
	</ItemGroup>

</Project>
