<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<Version>1.1.0</Version>
	</PropertyGroup>

	<PropertyGroup>
		<PackageId>WSCT.ACOS6</PackageId>
		<Description>A library for using WSCT with ACOS6 smartcards.</Description>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Description>
			Defines some commands for working with ACOS6 smartcards.
			It is intended for use at ENSICAEN, for educational purposes (e-payment and security).
		</Description>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\LICENSE.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="WSCT.Core" />
	</ItemGroup>

</Project>
