using System.Security.Cryptography;
using WSCT.ACOS6.Commands;
using WSCT.Core;
using WSCT.Core.Fluent.Helpers;
using WSCT.ISO7816;

namespace WSCT.ACOS6.Security.TripleDes
{
    public static class Cryptography
    {
        public static byte[] Create3DESShortAuthenticationData(this byte[] challenge, byte[] key)
        {
            var data = new byte[8];
            challenge.CopyTo(data, 4);

            var key3DES = TripleDES.Create();
            key3DES.Key = key;
            key3DES.IV = new byte[8];

            using var encryptor = key3DES.CreateEncryptor();

            return encryptor
                .TransformFinalBlock(data, 0, data.Length)
                .AsSpan(0, 4)
                .ToArray();
        }

        public static byte[] Create3DESAuthenticationData(this byte[] challenge, byte[] key)
        {
            var key3DES = TripleDES.Create();
            key3DES.Key = key;
            key3DES.IV = new byte[8];

            using var encryptor = key3DES.CreateEncryptor();

            return encryptor
                .TransformFinalBlock(challenge, 0, challenge.Length)
                .AsSpan(0, 8)
                .ToArray();
        }

        internal static byte[] CreateSessionKey(byte[] cardRandom, byte[] cardKey, byte[] terminalRandom, byte[] terminalKey)
        {
            var sessionKey = new byte[16];

            // KsL = 3DES (3DES (RNDC, KC), KT)
            cardRandom
                .Create3DESAuthenticationData(cardKey)
                .Create3DESAuthenticationData(terminalKey)
                .CopyTo(sessionKey, 0);

            // The operation REV (KT) is the exchange of the left and right half of KT.
            var reversedKeyTerminal = new byte[16];
            terminalKey.AsSpan(8, 8).CopyTo(reversedKeyTerminal.AsSpan(0));
            terminalKey.AsSpan(0, 8).CopyTo(reversedKeyTerminal.AsSpan(8));

            // KsR = 3DES (RNDT, REV (KT))
            terminalRandom
                .Create3DESAuthenticationData(reversedKeyTerminal)
                .CopyTo(sessionKey, 8);

            return sessionKey;
        }

        public static bool AuthenticateWithShortKey(this ICardChannel cardChannel, byte keyId, byte[] shortKey)
        {
            // GET CHALLENGE (4 bytes)
            var challenge = Array.Empty<byte>();
            new GetChallengeCommand(0x04)
                .Transmit(cardChannel)
                .ThrowIfNotSuccess()
                .ThrowIfSWNot9000()
                .Then((c, r) => challenge = r.Udr);

            // EXTERNAL AUTHENTICATE (DF Short Key 83)
            var authentication = new CommandAPDU(0x00, 0x82, 0x00, keyId, 0x04, challenge.Create3DESShortAuthenticationData(shortKey))
                .Transmit(cardChannel)
                .ThrowIfNotSuccess();

            return authentication.RApdu.StatusWord == 0x9000;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="cardChannel"></param>
        /// <param name="terminalRandom">8 bytes random number generated by the terminal (RNDT).</param>
        /// <param name="terminalKey">Terminal key (KT).</param>
        /// <param name="cardKey">Card key (KC)</param>
        /// <param name="sessionKey">Session key created during the mutual authentication process (Ks).</param>
        /// <returns></returns>
        public static bool MutualAuthenticate(this ICardChannel cardChannel, byte[] terminalRandom, byte[] terminalKey, byte[] cardKey, out byte[] sessionKey)
        {
            // GET CHALLENGE (8 bytes)
            var cardRandom = new GetChallengeCommand(0x08)
                .Transmit(cardChannel)
                .ThrowIfNotSuccess()
                .ThrowIfSWNot9000()
                .RApdu.Udr;

            // R1 = ENC (RNDC, KT)
            var r1 = cardRandom.Create3DESAuthenticationData(terminalKey);

            var r2 = Array.Empty<byte>();
            // EXTERNAL AUTHENTICATE (R1, RNDT)
            new CommandAPDU(0x00, 0x82, 0x82, 0x81, 0x10, r1.Concat(terminalRandom).ToArray())
                .Transmit(cardChannel)
                .ThrowIfNotSuccess()
                .ChainIf(r => r.Sw1 == 0x61, r => new CommandAPDU(0x00, 0xC0, 0x00, 0x00, r.Sw2), cardChannel)
                .ThrowIfNotSuccess()
                .OnStatusWord(sw => sw == 0x9000, (c, r) => r2 = r.Udr);

            // Compute session key Ks
            sessionKey = CreateSessionKey(cardRandom, cardKey, terminalRandom, terminalKey);

            var result = terminalRandom
                .Create3DESAuthenticationData(sessionKey);

            return result.SequenceEqual(r2);
        }
    }
}
