<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Library</OutputType>
		<Version>2.1.0</Version>
	</PropertyGroup>

	<PropertyGroup>
		<PackageId>WSCT.Layers.ACOS6</PackageId>
		<GeneratePackageOnBuild>False</GeneratePackageOnBuild>
	</PropertyGroup>

	<PropertyGroup>
		<AssemblyName>Layers.ACOS6</AssemblyName>
		<Description>Layer ACOS6 for WSCT.</Description>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="WSCT.Core" />
	</ItemGroup>
</Project>